### ISSUE TITLE
Homepage - Menubalk :Overgang items aanklikken

### ISSUE THREAD

**Issue by cboonstra** [ASRRtechnologies/asrr-nextjs#39]
**Voor de items in de menubalk:**

- [ ] Zelfde overgang bij het aanklikken als bij eerste afbeelding hieronder. --> dat de tekst wordt gevuld met de kleur van de muis. 

- [ ] Toevoegen van onderdeel "Vacatures" in de menubalk.

<img width="1393" alt="Schermafbeelding 2020-07-22 om 11 35 37" src="https://user-images.githubusercontent.com/68586686/88160810-7a7fe800-cc0f-11ea-8a36-6254e353aad3.png">

<img width="371" alt="Schermafbeelding 2020-07-22 om 11 32 20" src="https://user-images.githubusercontent.com/68586686/88160508-034a5400-cc0f-11ea-8ab6-993e807d956a.png">

**Comment by ReangeloJ** [comment]
Did this for all links on the site
