### ISSUE TITLE
Homepage - Tekst begin scherm

### ISSUE THREAD

**Issue by cboonstra** [ASRRtechnologies/asrr-nextjs#40]
Dit moet worden “Innovative software development”. 

<img width="492" alt="Schermafbeelding 2020-07-22 om 11 39 15" src="https://user-images.githubusercontent.com/68586686/88161205-fa0db700-cc0f-11ea-809a-ea6c0e9f8a05.png">

**Comment by ReangeloJ** [comment]
done
