### ISSUE TITLE
Homepage - sectie footer: Volgorde gegevens

### ISSUE THREAD

**Issue by cboonstra** [ASRRtechnologies/asrr-nextjs#41]
Dit veranderen naar huidig adres en get directions moet onder het adres ipv de email. 

<img width="579" alt="Schermafbeelding 2020-07-22 om 11 40 52" src="https://user-images.githubusercontent.com/68586686/88161374-34775400-cc10-11ea-84c6-cd71bc71611e.png">

**Comment by ReangeloJ** [comment]
done
