### ISSUE TITLE
Homepage - sectie "WERKGEVERS ERVARINGEN"

### ISSUE THREAD

**Issue by cboonstra** [ASRRtechnologies/asrr-nextjs#45]
- [ ]  Maak een onderdeel op de homepage met drie kolommen met de ervaringen van vorige werkgevers.

<img width="709" alt="Schermafbeelding 2020-07-22 om 12 18 31" src="https://user-images.githubusercontent.com/68586686/88165107-76ef5f80-cc15-11ea-9428-28084e5d9a9b.png">

**Comment by ReangeloJ** [comment]
Done
