### ISSUE TITLE
Homepage - sectie "contact"

### ISSUE THREAD

**Issue by cboonstra** [ASRRtechnologies/asrr-nextjs#46]
- [x] Maak een sectie met een doorverwijzing naar het contact formulier ipv een heel contact formulier onderaan elke pagina, voorbeeld hieronder. 

<img width="745" alt="Schermafbeelding 2020-07-22 om 12 19 22" src="https://user-images.githubusercontent.com/68586686/88165223-a8682b00-cc15-11ea-9e72-3dde2433cae3.png">

**Comment by ReangeloJ** [comment]
done
