### ISSUE TITLE
Homepage - "Cliënten"

### ISSUE THREAD

**Issue by cboonstra** [ASRRtechnologies/asrr-nextjs#52]
- [ ] Zoals Amit al zei: dit is misschien een beetje overbodig om hier tekst bij te zetten want dat blijkt al uit de portfolio. Logo's van de bedrijven is voldoende.

<img width="1387" alt="Schermafbeelding 2020-07-28 om 11 34 33" src="https://user-images.githubusercontent.com/68586686/88647491-5700e580-d0c6-11ea-87c7-f3d0a7e740de.png">

**Comment by ReangeloJ** [comment]
Zou ik dan ipv Clienten in groot alleen Zij gingen u voor in het groot?

**Comment by Amar97** [comment]
Ja en ik denk die logo's zwart
