### ISSUE TITLE
Homepage - knop onder introductie tekst

### ISSUE THREAD

**Issue by cboonstra** [ASRRtechnologies/asrr-nextjs#62]
![image](https://user-images.githubusercontent.com/68586686/90507236-daf23e80-e155-11ea-895c-9bed15ee8384.png)

- [x] De knop is hier zwart. Is dat de bedoeling?

**Comment by ReangeloJ** [comment]
Ja text moet er nog inkomen. Witte knop is niet mooi oo witte achtergrond

**Comment by Amar97** [comment]
ja heb het gefixt. Haha nee lotte bedoelde dat ie gwn leeg is, de kleur is goed
